#!/usr/bin/env bash
# Transfers a file to a server
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no $1 "$3@$2:/home/$3/" -i $4 
fi
