#!/usr/bin/env bash
# This script is displaying "Best school" using the while loop

i=0
while [ $i -lt 10 ]
do
        if [ $i -eq 8 ];
	then
		echo "Hi"
	else
		echo "Best School"
	fi
        ((i += 1))
done
